### ISSUE TITLE
Cannot find mapbox-gl after upgrade to 0.8.7

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#36]
Adding `"mapbox-gl": "^0.42.0",` to devDependencies solves the issue, however.

```
DCP-APPLE-1770:labs-community-portal mgardner$ ember s
Cannot find module 'mapbox-gl'
Error: Cannot find module 'mapbox-gl'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Class.treeForVendor (/Users/mgardner/labs-community-portal/node_modules/ember-mapbox-gl/index.js:25:58)
    at Class._treeFor (/Users/mgardner/labs-community-portal/node_modules/ember-cli/lib/models/addon.js:557:33)
    at Class.treeFor (/Users/mgardner/labs-community-portal/node_modules/ember-cli/lib/models/addon.js:517:21)
    at project.addons.reduce (/Users/mgardner/labs-community-portal/node_modules/ember-cli/lib/broccoli/ember-app.js:630:25)
    at Array.reduce (<anonymous>)
    at EmberApp.addonTreesFor (/Users/mgardner/labs-community-portal/node_modules/ember-cli/lib/broccoli/ember-app.js:628:32)
    at EmberApp._processedVendorTree (/Users/mgardner/labs-community-portal/node_modules/ember-cli/lib/broccoli/ember-app.js:1115:24)
    at EmberApp._processedExternalTree (/Users/mgardner/labs-community-portal/node_modules/ember-cli/lib/broccoli/ember-app.js:1143:25)
```

**Comment by kturney** [comment]
strange. the blueprint should have added that to the app
